---
title: "ACB"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "#FEFEFE"
      fg: "#1c0d02"
      primary:   "#452674"
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
    navbar:
        - { title: "Daniel Alejo Rodríguez", align: right}
        - { icon: "fa-brands fa-dochub",align: right}
    orientation: columns
    vertical_layout: fill
---

<style>
.navbar-brand {
color:gold!important;
}
</style>

```{r setup, include=FALSE}
suppressMessages(library(flexdashboard))
# library(bigrquery)
suppressMessages(library(readr))
suppressMessages(library(tidyr))
suppressMessages(library(dplyr))
suppressMessages(library(DT))
suppressMessages(library(ggplot2))
suppressMessages(library(ggrepel))
suppressMessages(library(reactable))
suppressMessages(library(crosstalk))
suppressMessages(library(plotly))
suppressMessages(library(ggiraph))
suppressMessages(library(htmltools))

```

# TEAM STATS <i class="fa-solid fa-users-line"></i>
## Column {data-width="750"}
### Stats table

```{r}
# Querying ----------------------------------------------------------------
# project <- Sys.getenv("MY_PROJECT")
# dataset <- Sys.getenv("MY_DATASET")
# table <- Sys.getenv("MY_TABLE")

team_stats <- readr::read_delim("data.csv", delim = ",", locale = readr::locale(encoding = "UTF-8"))        # ISO-8859-1, latin1
team_stats <- team_stats[7:dim(team_stats)[1], ]
team_stats <- tidyr::separate(team_stats,
                              col = 1,
                              into = c("team", "season", "home_away", "total_games", "points_avg", "rebounds_avg",
                                       "assists_avg", "steals_avg", "defensive_blocks_avg", "turnovers_avg",
                                       "player_efficiency_rating_avg", "plus_minus_avg"),
                              sep = ",")

team_stats <- team_stats |> 
                mutate(
                  team = as.character(team),
                  season = as.character(season),
                  home_away = as.character(home_away),
                  total_games = as.double(total_games),
                  points_avg = as.double(points_avg),
                  rebounds_avg = as.double(rebounds_avg),
                  assists_avg = as.double(assists_avg),
                  steals_avg = as.double(steals_avg),
                  defensive_blocks_avg = as.double(defensive_blocks_avg),
                  turnovers_avg = as.double(turnovers_avg),
                  player_efficiency_rating_avg = as.double(player_efficiency_rating_avg),
                  plus_minus_avg = as.double(plus_minus_avg),
                  points_avg_norm = (points_avg - min(points_avg)) / (max(points_avg) - min(points_avg))
                ) |>
                group_by(team) |> 
                arrange(team, home_away, desc(season))

# Background color
orange_pal <- function(x) rgb(colorRamp(c("#fee9cc", "#fca52a"))(x), maxColorValue = 255)

# Background style to visually distinguish sticky columns
sticky_style <- list(backgroundColor = "#f7f7f7")

reactable(
  team_stats,
  defaultColDef = colDef(
    header = function(col) { stringr::str_to_title(gsub("_", " ", col)) },
    align = "center",
    minWidth = 150,
    headerStyle = list(background = "#f7f7f8")
  ),
  columns = list(
    team = colDef(
      style = JS("function(rowInfo, column, state) {
        const firstSorted = state.sorted[0]
        if (!firstSorted || firstSorted.id === 'team') {
          const prevRow = state.pageRows[rowInfo.viewIndex - 1]
          if (prevRow && rowInfo.values['team'] === prevRow['team']) {
            return {
              color: 'transparent',
              backgroundColor: 'white'
            }
          }
        }
      }"),
      sticky = "left",
      headerStyle = sticky_style
    ),
    season = colDef(
      sticky = "left",
      style = sticky_style,
      headerStyle = sticky_style
    ),
    home_away = colDef(
      sticky = "left",
      style = sticky_style,
      headerStyle = sticky_style
    ),
    points_avg = colDef(
      style = function(value, index) {
        norm <- team_stats$points_avg_norm[index]
        color <- orange_pal(norm)
        list(background = color, fontWeight = "bold")
      }
    ),
    points_avg_norm = colDef(show = FALSE),
    plus_minus_avg = colDef(
      style = JS("function(rowInfo) {
        const value = rowInfo.values['plus_minus_avg']
        let color
        if (value > 0) {
          color = '#008000'
        } else if (value < 0) {
          color = '#e00000'
        } else {
          color = '#777'
        }
        return { color: color, fontWeight: 'bold' }
      }")
    )
  ),
  outlined = TRUE,
  filterable = TRUE,
  resizable = TRUE,
  wrap = FALSE,
  bordered = TRUE,
  defaultPageSize = 24
)

```

## {.tabset .tabset-fade}
### Graphic by Local team
```{r}
# Local Analysis - Aggregated Data for Chart (Averages by Team)
avg_data_home <- team_stats |>
  filter(home_away == 'home') |>
  group_by(team, season) |>
  summarise(
    assists_avg_team = mean(assists_avg, na.rm = TRUE),
    points_avg_team = mean(points_avg, na.rm = TRUE),
    .groups = "drop"
  )

data_shared_home <- SharedData$new(avg_data_home)

p_home <- ggplot(data_shared_home, aes(x = assists_avg_team, y = points_avg_team,
                             color = team, text = paste("Team:", team, " - Season:", season))) +
  geom_point(size = 4, alpha = 0.8) +
  geom_text(aes(label = team), vjust = -1.2, size = 3, check_overlap = TRUE) +
  labs(title = "Local Analysis - Points vs Assists by Team",
       x = "Average Assists per Team", 
       y = "Average Points per Team") +
  theme_minimal(base_size = 12) +
  theme(legend.position = "right",
        plot.margin = margin(t = 10, r = 10, b = 80, l = 50))

plotly_home <- ggplotly(p_home, tooltip = "text")

bscols(
  widths = c(4, 4, NA),
  tags$div(
    style = "margin-left: 50px;",
    filter_select("season", "Season:", data_shared_home, ~season, multiple = TRUE)
  ),
  filter_select("team", "Team:", data_shared_home, ~team, multiple = TRUE)
)

plotly_home
```

### Graphic by Visit team
```{r}
# Visitor Analysis - Aggregated Data for Chart (Averages by Team)
avg_data_away <- team_stats |>
  filter(home_away == 'away') |>
  group_by(team, season) |>
  summarise(
    assists_avg_team = mean(assists_avg, na.rm = TRUE),
    points_avg_team = mean(points_avg, na.rm = TRUE),
    .groups = "drop"
  )

data_shared_away <- SharedData$new(avg_data_away)

p_away <- ggplot(data_shared_away, aes(x = assists_avg_team, y = points_avg_team,
                             color = team, text = paste("Team:", team, " - Season:", season))) +
  geom_point(size = 4, alpha = 0.8) +
  geom_text(aes(label = team), vjust = -1.2, size = 3, check_overlap = TRUE) +
  labs(title = "Visitor Analysis - Points vs Assists by Team",
       x = "Average Assists per Team", 
       y = "Average Points per Team") +
  theme_minimal(base_size = 12) +
  theme(legend.position = "right",
        plot.margin = margin(t = 10, r = 10, b = 80, l = 50))

plotly_away <- ggplotly(p_away, tooltip = "text")

bscols(
  widths = c(4, 4, NA),
  tags$div(
    style = "margin-left: 50px;",
    filter_select("season", "Season:", data_shared_away, ~season, multiple = TRUE)
  ),
  filter_select("team", "Team:", data_shared_away, ~team, multiple = TRUE)
)

plotly_away
```


# PLAYER STATS <i class="fa-solid fa-basketball"></i>
## Column {data-width="100%"}

<iframe width="100%" height="100%" src="https://lookerstudio.google.com/embed/reporting/e25cc0db-e5f5-44e6-9096-f2688cceee4a/page/kUVYD" frameborder="0" style="border:0" allowfullscreen></iframe>


# PLAYERS PLAYED TOGETHER <i class="fa-solid fa-arrows-down-to-people"></i>
## Column {data-width="100%"}
### Stats table

```{r}

```